apiVersion: v1
kind: Secret
metadata:
  name: yugabyte-secret
  namespace: assessment
type: Opaque
data:
  DB_USER: eXVnYWJ5dGU=  # Base64 encoded value of "yugabyte"
  DB_HOST: eWItdHNlcnZlcnMueWItZGVtby5zdmMuY2x1c3Rlci5sb2NhbA==  # Base64 encoded value of "yb-tservers.yb-demo.svc.cluster.local"
  DB_NAME: eXVnYWJ5dGU=  # Base64 encoded value of "yugabyte"
  DB_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded value of "password"
  DB_PORT: NTQzMw==  # Base64 encoded value of "5433"

