apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
        - name: apisix
          image: apache/apisix:latest
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: assessment
spec:
  selector:
    app: apisix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
  type: LoadBalancer
