apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: assessment
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: trillsss/order-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: yugabyte-secret
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: assessment
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
