apiVersion: v1
kind: Secret
metadata:
  name: yugabyte-secret
type: Opaque
data:
  DB_USER: eXVnYWJ5dGU=
  DB_HOST: eWItdHNlcnZlcnMueWItZGVtby5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_NAME: eXVnYWJ5dGU=
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_PORT: NTQzMw==
