name: Deploy to Local Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl to use local Minikube
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl config use-context minikube

      - name: Create Namespace 'assessment'
        run: |
          kubectl create namespace assessment --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kubernetes Secrets
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: yugabyte-secret
            namespace: assessment
          type: Opaque
          data:
            DB_USER: $(echo -n "${{ secrets.DB_USER }}" | base64)
            DB_HOST: $(echo -n "${{ secrets.DB_HOST }}" | base64)
            DB_NAME: $(echo -n "${{ secrets.DB_NAME }}" | base64)
            DB_PASSWORD: $(echo -n "${{ secrets.DB_PASSWORD }}" | base64)
            DB_PORT: $(echo -n "${{ secrets.DB_PORT }}" | base64)
          EOF

      - name: Deploy User and Order Services
        run: |
          kubectl apply -f kubernetes/user-service.yaml -n assessment
          kubectl apply -f kubernetes/order-service.yaml -n assessment
          kubectl apply -f kubernetes/secrets.yaml -n assessment

      - name: Verify Deployment
        run: |
          kubectl get pods -n assessment
          kubectl get svc -n assessment
