name: Deploy to Local Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl to use Minikube
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          kubectl config use-context minikube

      - name: Create Namespace 'assessment' If Not Exists
        run: |
          if ! kubectl get namespace assessment >/dev/null 2>&1; then
            echo "Namespace 'assessment' does not exist. Creating it now..."
            kubectl create namespace assessment
          else
            echo "Namespace 'assessment' already exists. Skipping creation."
          fi

      - name: Deploy Kubernetes Secrets
        run: |
          kubectl apply -f kubernetes/secrets.yaml -n assessment

      - name: Deploy User and Order Services
        run: |
          kubectl apply -f kubernetes/user-service.yaml -n assessment
          kubectl apply -f kubernetes/order-service.yaml -n assessment
          kubectl apply -f kubernetes/secrets.yaml -n assessment

      - name: Verify Deployment
        run: |
          kubectl get namespaces
          kubectl get pods -n assessment
          kubectl get svc -n assessment
